name: Deploying AI model to PROD server

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH and clone repository
        env:
          SSH_PRIVATE_KEY: ${{ vars.SSH_PRIVATE_KEY }}
          LIGHTSAIL_IP: ${{ vars.LIGHTSAIL_IP }}
          
        run: |
          set -e  # Exit the script if any command fails

          echo "Setting up SSH private key"
          mkdir -p ~/.ssh
          
          # Ensure that the private key is not already present
          if [ ! -f ~/.ssh/id_rsa ]; then
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo "SSH private key added successfully."
          else
            echo "SSH private key already exists."
          fi

          # Add GitHub to known hosts to avoid SSH prompt
          echo "Adding GitHub to known hosts"
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          
          # Set up LightSail SSH and clone the repo
          echo "Connecting to LightSail instance"
          ssh -o StrictHostKeyChecking=no ubuntu@$LIGHTSAIL_IP << 'EOF'
            set -e  # Exit if any command fails

            echo "Checking for deployment directory on LightSail..."
            mkdir deployment 
            echo "Creating deployment directory on LightSail..."
            cd deployment
            echo "Created deployment directory on LightSail..."
            if [ -d "deployment" ]; then
              echo "Deployment directory exists. Pulling the latest code..."
              cd deployment
              pwd
              git pull origin ${{ github.ref_name }}
            else
              echo "Deployment directory not found. Cloning the repository..."
              git clone git@github.com:4li4bdullah/django-templates.git
              echo "Cloned the repository successfully."
            fi
          EOF

          echo "Deployment process completed."
